"""Tests for CodeGraphBuilder across repository entities and relationships."""

from pathlib import Path
import pytest

from analysis.analyzer import RepositoryAnalyzer
from analysis.graph_builder import CodeGraphBuilder
from analysis.graph_models import CodeGraph, NodeType, RelationshipType


@pytest.fixture
def sample_repo_path() -> Path:
    return Path(__file__).resolve().parent.parent / "fixtures" / "sample_repo"


@pytest.fixture
def built_graph(sample_repo_path: Path) -> CodeGraph:
    analyzer = RepositoryAnalyzer()
    index = analyzer.analyze_repository(str(sample_repo_path))
    builder = CodeGraphBuilder()
    return builder.build_graph(index)


class TestCodeGraphBuilder:
    """Verify nodes and relationship edges generated by CodeGraphBuilder."""

    def test_nodes_created(self, built_graph: CodeGraph) -> None:
        """Graph contains repo, dir, file, module, class, and function nodes."""
        node_types = {n.type for n in built_graph.nodes}
        assert NodeType.REPOSITORY in node_types
        assert NodeType.DIRECTORY in node_types
        assert NodeType.FILE in node_types
        assert NodeType.MODULE in node_types
        assert NodeType.CLASS in node_types
        assert NodeType.FUNCTION in node_types

        # Check specific nodes
        node_ids = {n.id for n in built_graph.nodes}
        assert "repo:sample_repo" in node_ids
        assert "dir:src" in node_ids
        assert "file:src/app.py" in node_ids
        assert "module:src.app" in node_ids
        assert "class:src/models.py:User" in node_ids
        assert "func:src/utils.py:hash_file" in node_ids

    def test_contains_edges(self, built_graph: CodeGraph) -> None:
        """CONTAINS edges link repo to dirs/files, and dirs to files."""
        contains_edges = [e for e in built_graph.edges if e.type == RelationshipType.CONTAINS]
        assert len(contains_edges) > 0

        # Repo contains src
        repo_src = any(e.source == "repo:sample_repo" and e.target == "dir:src" for e in contains_edges)
        assert repo_src

        # dir:src contains file:src/app.py
        src_app = any(e.source == "dir:src" and e.target == "file:src/app.py" for e in contains_edges)
        assert src_app

    def test_defines_edges(self, built_graph: CodeGraph) -> None:
        """DEFINES edges link files to classes and functions with source lines."""
        defines_edges = [e for e in built_graph.edges if e.type == RelationshipType.DEFINES]
        assert len(defines_edges) > 0

        # src/models.py DEFINES User
        user_def = next(
            (e for e in defines_edges if e.source == "file:src/models.py" and "User" in e.target),
            None,
        )
        assert user_def is not None
        assert user_def.line == 8

        # src/utils.py DEFINES hash_file
        hash_def = next(
            (e for e in defines_edges if e.source == "file:src/utils.py" and "hash_file" in e.target),
            None,
        )
        assert hash_def is not None
        assert hash_def.line == 7

    def test_imports_edges(self, built_graph: CodeGraph) -> None:
        """IMPORTS edges link files to imported modules."""
        import_edges = [e for e in built_graph.edges if e.type == RelationshipType.IMPORTS]
        assert len(import_edges) > 0

        # src/app.py imports flask
        flask_imp = next(
            (e for e in import_edges if e.file == "src/app.py" and "flask" in e.target),
            None,
        )
        assert flask_imp is not None
        assert flask_imp.line > 0

    def test_calls_edges_and_resolution(self, built_graph: CodeGraph) -> None:
        """CALLS edges are created and resolved where possible."""
        call_edges = [e for e in built_graph.edges if e.type == RelationshipType.CALLS]
        assert len(call_edges) > 0

        # Every call edge must have file and line
        for e in call_edges:
            assert e.file != ""
            assert e.line > 0
            assert e.confidence > 0.0

    def test_test_edges(self, built_graph: CodeGraph) -> None:
        """TESTS edges link test files/functions to tested files/functions."""
        test_edges = [e for e in built_graph.edges if e.type == RelationshipType.TESTS]
        assert len(test_edges) > 0

        # tests/test_app.py TESTS src/app.py
        app_test = next(
            (e for e in test_edges if "test_app.py" in e.source and "app.py" in e.target),
            None,
        )
        assert app_test is not None

        # test_hash_file TESTS hash_file
        fn_test = next(
            (e for e in test_edges if "test_hash_file" in e.source and "hash_file" in e.target),
            None,
        )
        assert fn_test is not None

    def test_inheritance_edges(self, tmp_path: Path) -> None:
        """INHERITS edges are created for class hierarchies."""
        (tmp_path / "animals.py").write_text('''
class Animal:
    pass

class Mammal(Animal):
    pass

class Dog(Mammal):
    pass
''')
        analyzer = RepositoryAnalyzer()
        index = analyzer.analyze_repository(str(tmp_path))
        builder = CodeGraphBuilder()
        graph = builder.build_graph(index)

        inherits_edges = [e for e in graph.edges if e.type == RelationshipType.INHERITS]
        assert len(inherits_edges) == 2

        # Dog inherits Mammal
        dog_edge = next((e for e in inherits_edges if "Dog" in e.source and "Mammal" in e.target), None)
        assert dog_edge is not None
        assert dog_edge.resolved is True

        # Mammal inherits Animal
        mammal_edge = next((e for e in inherits_edges if "Mammal" in e.source and "Animal" in e.target), None)
        assert mammal_edge is not None
        assert mammal_edge.resolved is True

    def test_graph_statistics(self, built_graph: CodeGraph) -> None:
        """Verify summary statistics calculated on built graph."""
        stats = built_graph.statistics
        assert stats.total_nodes > 0
        assert stats.total_edges > 0
        assert len(stats.relationships_by_type) > 0
        assert "DEFINES" in stats.relationships_by_type
        assert "CONTAINS" in stats.relationships_by_type
        assert "IMPORTS" in stats.relationships_by_type
